// =============================================================================
// BASE ENTITY TYPES
// =============================================================================
// These types correspond directly to database table structures

/**
 * Source type for flashcards - indicates how the flashcard was created
 */
export type FlashcardSource = 'ai-full' | 'ai-edited' | 'manual';

/**
 * Base flashcard entity type corresponding to public.flashcards table
 */
export interface FlashcardEntity {
  id: string;
  user_id: string;
  generation_id: string | null;
  front: string;
  back: string;
  source: FlashcardSource;
  created_at: string;
  updated_at: string;
}

/**
 * Base generation entity type corresponding to public.generations table
 */
export interface GenerationEntity {
  id: string;
  user_id: string;
  model: string | null;
  source_text_hash: string;
  source_text_length: number;
  generated_count: number;
  accepted_unedited_count: number | null;
  accepted_edited_count: number | null;
  rejected_count: number;
  generation_duration: number;
  created_at: string;
  updated_at: string;
}

/**
 * Base generation error log entity type corresponding to public.generation_error_logs table
 */
export interface GenerationErrorLogEntity {
  id: string;
  user_id: string;
  model: string | null;
  source_text_hash: string | null;
  source_text_length: number | null;
  error_code: string | null;
  error_message: string;
  created_at: string;
}

// =============================================================================
// DTO TYPES (Data Transfer Objects)
// =============================================================================
// These types represent data structures sent in API responses

/**
 * Flashcard DTO for API responses - excludes sensitive user_id field
 */
export type FlashcardDTO = Omit<FlashcardEntity, 'user_id'>;

/**
 * Generation log DTO for API responses - excludes sensitive user_id field
 */
export type GenerationLogDTO = Omit<GenerationEntity, 'user_id'>;

/**
 * Pagination metadata for list responses
 */
export interface PaginationInfo {
  total_items: number;
  total_pages: number;
  current_page: number;
  limit: number;
}

/**
 * Paginated list response for flashcards
 */
export interface FlashcardsListResponse {
  data: FlashcardDTO[];
  pagination: PaginationInfo;
}

/**
 * Flashcard candidate generated by AI (before user review)
 */
export interface FlashcardCandidate {
  front: string;
  back: string;
  source: FlashcardSource;
}

/**
 * Response for AI generation endpoint
 */
export interface GenerationResponse {
  generation_id: string;
  model: string | null;
  source_text_hash: string;
  source_text_length: number;
  generated_count: number;
  rejected_count: number;
  generation_duration: number;
  created_at: string;
  candidates: FlashcardCandidate[];
}

// =============================================================================
// COMMAND TYPES (Request DTOs)
// =============================================================================
// These types represent data structures sent in API requests

/**
 * Command for creating a single flashcard
 */
export interface CreateFlashcardCommand {
  front: string;
  back: string;
  source: FlashcardSource;
  generation_id?: string | null;
}

/**
 * Command for creating multiple flashcards (bulk operation)
 */
export type CreateFlashcardsCommand = CreateFlashcardCommand[];

/**
 * Command for updating an existing flashcard - only content fields are updatable
 */
export interface UpdateFlashcardCommand {
  front?: string;
  back?: string;
}

/**
 * Command for generating flashcards using AI
 */
export interface GenerateFlashcardsCommand {
  source_text: string;
  model?: string;
}

/**
 * Command for updating generation log with review session results
 */
export interface UpdateGenerationCommand {
  accepted_unedited_count: number;
  accepted_edited_count: number;
  rejected_count: number;
}

// =============================================================================
// API ERROR TYPES
// =============================================================================

/**
 * Standard API error response structure
 */
export interface ApiError {
  error: string;
  message: string;
  details?: Record<string, any>;
}

/**
 * Validation error details for form submissions
 */
export interface ValidationError {
  field: string;
  message: string;
}

/**
 * API error response with validation details
 */
export interface ValidationApiError extends ApiError {
  validation_errors: ValidationError[];
}

// =============================================================================
// UTILITY TYPES
// =============================================================================

/**
 * Generic paginated response wrapper
 */
export interface PaginatedResponse<T> {
  data: T[];
  pagination: PaginationInfo;
}

/**
 * Generic API response wrapper for success cases
 */
export interface ApiResponse<T> {
  data: T;
  message?: string;
}

/**
 * Query parameters for listing flashcards
 */
export interface FlashcardsListQuery {
  page?: number;
  limit?: number;
  search?: string;
}

// =============================================================================
// VIEW MODEL TYPES
// =============================================================================
// These types represent UI-specific data structures with additional state

/**
 * Review candidate view model - extends FlashcardCandidate with UI state
 */
export interface ReviewCandidateViewModel extends FlashcardCandidate {
  id: string; // Unique client-side identifier (e.g. from uuid)
  status: 'pending' | 'accepted' | 'edited' | 'rejected';
  originalFront: string; // Original content for tracking edits
  originalBack: string; // Original content for tracking edits
}
